---
# tasks file for mywebsite
Tasks:
 - name: Install Apache 
   apt: pkg=apache2 state=installed
   register: apacheinstalled 
   notify:
    - Restart Apache
 
 - name: Disable Default Size
   when: apacheinstalled|success
   file: dest=/etc/httpd/conf.d/welcome.conf state=absent

 - name: Vhosts config 
   when: apacheinstalled|success
   register: vhostconfig
   template: src=vhost.j2 dest=/etc/httpd/conf.d/{{ title }}.conf owner=root group=root
   
 - name: Create webroot 
   when: vhostconfig|success
   register: webrootcreated
   file: dest={{ document_root }} mode=775 state=directory owner=apache group=apache 

 - name: Copy Index file 
   when: webrootcreated|success
   copy: src=index.html dest={{ document_root }} mode=755 owner=apache group=apache

 - name: webroot permissions 
   when: wberootcreated|success
   file: dest={{ document_root }} mode=775 state=directory owner=apache group=apache recurse=yes
   notify:
    - Restart Apache
